﻿apiRules:
- exclude:
      uidRegex: ^System\.Object
      type: Type
- exclude:
      uidRegex: ^Microsoft\.AspNetCore\.Mvc\.Controller
      type: Type
- exclude:
      uidRegex: ^Microsoft\.EntityFrameworkCore
      type: Type
- exclude:
      uidRegex: ^Automatonymous
      type: Type
